import { router, useFocusEffect } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { getAccountSyncData } from "../services/accountSync";
import { deleteNotification, markNotificationRead } from "../services/api";

type AlertFilter = "all" | "critical" | "warning" | "info";

type SmartAlert = {
  id: string;
  title: string;
  message: string;
  level: "critical" | "warning" | "info";
  source: "backend" | "sensor" | "diagnosis" | "system";
  createdAt?: string | null;
  isRead?: boolean;
  raw?: any;
};

export default function AlertsScreen() {
  const [backendNotifications, setBackendNotifications] = useState<any[]>([]);
  const [diagnoses, setDiagnoses] = useState<any[]>([]);
  const [latestReading, setLatestReading] = useState<any | null>(null);
  const [devices, setDevices] = useState<any[]>([]);
  const [sectors, setSectors] = useState<any[]>([]);
  const [dashboard, setDashboard] = useState<any | null>(null);

  const [filter, setFilter] = useState<AlertFilter>("all");
  const [loading, setLoading] = useState(false);
  const [actionLoadingId, setActionLoadingId] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  async function loadAlerts() {
    try {
      setLoading(true);
      setErrorMessage("");

      const data = await getAccountSyncData();

      setBackendNotifications(
        Array.isArray(data.notifications) ? data.notifications : [],
      );
      setDiagnoses(Array.isArray(data.diagnoses) ? data.diagnoses : []);
      setLatestReading(data.latestReading || null);
      setDevices(Array.isArray(data.devices) ? data.devices : []);
      setSectors(Array.isArray(data.sectors) ? data.sectors : []);
      setDashboard(data.dashboard || null);
    } catch (error: any) {
      setErrorMessage(
        error?.message || "Could not load alerts from this account.",
      );
    } finally {
      setLoading(false);
    }
  }

  useFocusEffect(
    useCallback(() => {
      loadAlerts();
    }, []),
  );

  const alerts = useMemo(() => {
    return buildSmartAlerts({
      backendNotifications,
      diagnoses,
      latestReading,
      devices,
      sectors,
      dashboard,
    });
  }, [
    backendNotifications,
    dashboard,
    devices,
    diagnoses,
    latestReading,
    sectors,
  ]);

  const filteredAlerts =
    filter === "all" ? alerts : alerts.filter((item) => item.level === filter);

  const criticalCount = alerts.filter(
    (item) => item.level === "critical",
  ).length;
  const warningCount = alerts.filter((item) => item.level === "warning").length;
  const infoCount = alerts.filter((item) => item.level === "info").length;
  const unreadCount = alerts.filter((item) => !item.isRead).length;

  async function handleMarkRead(item: SmartAlert) {
    if (item.source !== "backend") {
      Alert.alert(
        "Local Alert",
        "This alert was generated by the mobile app from sensors or diagnosis data.",
      );
      return;
    }

    const notificationId = getNotificationId(item.raw);

    if (!notificationId) {
      Alert.alert("Missing ID", "This notification does not have a valid ID.");
      return;
    }

    try {
      setActionLoadingId(item.id);
      await markNotificationRead(notificationId);
      await loadAlerts();
    } catch (error: any) {
      Alert.alert(
        "Action Failed",
        error?.message || "Could not mark notification as read.",
      );
    } finally {
      setActionLoadingId("");
    }
  }

  async function handleDelete(item: SmartAlert) {
    if (item.source !== "backend") {
      Alert.alert(
        "Local Alert",
        "This alert is generated automatically and cannot be deleted from backend.",
      );
      return;
    }

    const notificationId = getNotificationId(item.raw);

    if (!notificationId) {
      Alert.alert("Missing ID", "This notification does not have a valid ID.");
      return;
    }

    Alert.alert("Delete Alert", "Are you sure you want to delete this alert?", [
      {
        text: "Cancel",
        style: "cancel",
      },
      {
        text: "Delete",
        style: "destructive",
        onPress: async () => {
          try {
            setActionLoadingId(item.id);
            await deleteNotification(notificationId);
            await loadAlerts();
          } catch (error: any) {
            Alert.alert(
              "Delete Failed",
              error?.message || "Could not delete notification.",
            );
          } finally {
            setActionLoadingId("");
          }
        },
      },
    ]);
  }

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Pressable style={styles.backButton} onPress={() => router.back()}>
          <Text style={styles.backText}>‹ Back</Text>
        </Pressable>

        <Pressable
          style={styles.refreshButton}
          onPress={loadAlerts}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#118A5B" />
          ) : (
            <Text style={styles.refreshText}>Refresh</Text>
          )}
        </Pressable>
      </View>

      <Text style={styles.kicker}>ECOSENSE AI</Text>
      <Text style={styles.title}>Alerts</Text>
      <Text style={styles.subtitle}>
        Smart alerts synced from your web account, backend notifications, latest
        sensor readings and AI diagnosis history.
      </Text>

      {errorMessage ? (
        <View style={styles.noticeBox}>
          <Text style={styles.noticeTitle}>Backend Notice</Text>
          <Text style={styles.noticeText}>{errorMessage}</Text>
        </View>
      ) : null}

      <View style={styles.heroCard}>
        <Text style={styles.heroLabel}>Active Alerts</Text>
        <Text style={styles.heroNumber}>{alerts.length}</Text>
        <Text style={styles.heroText}>
          {criticalCount > 0
            ? "Critical attention is required now."
            : warningCount > 0
              ? "Warnings found. Please review farm conditions."
              : "No critical issue detected from current data."}
        </Text>

        <View style={styles.heroStats}>
          <MiniStat label="Critical" value={String(criticalCount)} danger />
          <MiniStat label="Warning" value={String(warningCount)} warning />
          <MiniStat label="Info" value={String(infoCount)} />
          <MiniStat label="Unread" value={String(unreadCount)} />
        </View>
      </View>

      <View style={styles.filterRow}>
        <FilterButton
          label="All"
          active={filter === "all"}
          onPress={() => setFilter("all")}
        />
        <FilterButton
          label="Critical"
          active={filter === "critical"}
          onPress={() => setFilter("critical")}
        />
        <FilterButton
          label="Warning"
          active={filter === "warning"}
          onPress={() => setFilter("warning")}
        />
        <FilterButton
          label="Info"
          active={filter === "info"}
          onPress={() => setFilter("info")}
        />
      </View>

      {filteredAlerts.length > 0 ? (
        filteredAlerts.map((item) => (
          <View key={item.id} style={styles.alertCard}>
            <View style={styles.alertTop}>
              <View style={[styles.levelIcon, getLevelIconStyle(item.level)]}>
                <Text style={styles.levelIconText}>
                  {getLevelIcon(item.level)}
                </Text>
              </View>

              <View style={{ flex: 1 }}>
                <View style={styles.titleRow}>
                  <Text style={styles.alertTitle}>{item.title}</Text>

                  {!item.isRead ? <View style={styles.unreadDot} /> : null}
                </View>

                <Text style={styles.alertMeta}>
                  {formatSource(item.source)} • {formatDate(item.createdAt)}
                </Text>
              </View>

              <Text style={[styles.levelBadge, getLevelBadgeStyle(item.level)]}>
                {item.level.toUpperCase()}
              </Text>
            </View>

            <Text style={styles.alertMessage}>{item.message}</Text>

            <View style={styles.actionRow}>
              <Pressable
                style={styles.smallButton}
                onPress={() => handleMarkRead(item)}
                disabled={actionLoadingId === item.id}
              >
                {actionLoadingId === item.id ? (
                  <ActivityIndicator color="#118A5B" />
                ) : (
                  <Text style={styles.smallButtonText}>
                    {item.source === "backend" ? "Mark Read" : "Local Alert"}
                  </Text>
                )}
              </Pressable>

              <Pressable
                style={styles.deleteButton}
                onPress={() => handleDelete(item)}
                disabled={actionLoadingId === item.id}
              >
                <Text style={styles.deleteButtonText}>Delete</Text>
              </Pressable>
            </View>
          </View>
        ))
      ) : (
        <View style={styles.emptyCard}>
          <Text style={styles.emptyIcon}>✓</Text>
          <Text style={styles.emptyTitle}>No alerts in this filter</Text>
          <Text style={styles.emptyText}>
            Try another filter or refresh account data.
          </Text>
        </View>
      )}

      <View style={styles.quickActions}>
        <Pressable
          style={styles.actionCard}
          onPress={() => router.push("/(tabs)/sensors" as any)}
        >
          <Text style={styles.actionTitle}>Open Sensors</Text>
          <Text style={styles.actionText}>Check latest readings</Text>
        </Pressable>

        <Pressable
          style={styles.actionCard}
          onPress={() => router.push("/reports" as any)}
        >
          <Text style={styles.actionTitle}>Open Reports</Text>
          <Text style={styles.actionText}>View farm summary</Text>
        </Pressable>
      </View>
    </ScrollView>
  );
}

function MiniStat({
  label,
  value,
  danger,
  warning,
}: {
  label: string;
  value: string;
  danger?: boolean;
  warning?: boolean;
}) {
  return (
    <View style={styles.miniStat}>
      <Text
        style={[
          styles.miniValue,
          danger && styles.dangerText,
          warning && styles.warningText,
        ]}
      >
        {value}
      </Text>
      <Text style={styles.miniLabel}>{label}</Text>
    </View>
  );
}

function FilterButton({
  label,
  active,
  onPress,
}: {
  label: string;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      style={[styles.filterButton, active && styles.filterButtonActive]}
      onPress={onPress}
    >
      <Text style={[styles.filterText, active && styles.filterTextActive]}>
        {label}
      </Text>
    </Pressable>
  );
}

function buildSmartAlerts({
  backendNotifications,
  diagnoses,
  latestReading,
  devices,
  sectors,
  dashboard,
}: {
  backendNotifications: any[];
  diagnoses: any[];
  latestReading: any | null;
  devices: any[];
  sectors: any[];
  dashboard: any | null;
}) {
  const list: SmartAlert[] = [];

  backendNotifications.forEach((item, index) => {
    list.push({
      id: `backend-${getNotificationId(item) || index}`,
      title:
        safeText(item?.title) ||
        safeText(item?.type) ||
        safeText(item?.subject) ||
        "Backend Notification",
      message:
        safeText(item?.message) ||
        safeText(item?.body) ||
        safeText(item?.description) ||
        "Notification received from backend.",
      level: normalizeLevel(item?.level || item?.severity || item?.type),
      source: "backend",
      createdAt: item?.createdAt || item?.updatedAt || item?.timestamp || null,
      isRead: Boolean(item?.isRead || item?.read || item?.seen),
      raw: item,
    });
  });

  if (!latestReading) {
    list.push({
      id: "system-no-sensors",
      title: "No Sensor Data",
      message:
        "No latest hardware readings were found for this account. Connect ESP32 and upload readings.",
      level: "warning",
      source: "system",
      isRead: false,
      createdAt: new Date().toISOString(),
    });
  } else {
    const temp = safeNumber(latestReading.temperature);
    const humidity = safeNumber(latestReading.humidity);
    const moisture = safeNumber(latestReading.soilMoisture);
    const soilTemp = safeNumber(latestReading.soilTemp);

    if (temp >= 35) {
      list.push({
        id: "sensor-critical-temp",
        title: "Critical Temperature",
        message: `Temperature is ${temp}°C. Plant stress risk is high. Cooling or shade action is required.`,
        level: "critical",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    } else if (temp >= 32) {
      list.push({
        id: "sensor-high-temp",
        title: "High Temperature",
        message: `Temperature is ${temp}°C. Monitor the crop and consider cooling actions.`,
        level: "warning",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    }

    if (moisture > 0 && moisture <= 20) {
      list.push({
        id: "sensor-critical-moisture",
        title: "Critical Soil Moisture",
        message: `Soil moisture is ${moisture}%. Irrigation may be required immediately.`,
        level: "critical",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    } else if (moisture > 0 && moisture <= 30) {
      list.push({
        id: "sensor-low-moisture",
        title: "Low Soil Moisture",
        message: `Soil moisture is ${moisture}%. Check irrigation schedule.`,
        level: "warning",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    }

    if (humidity > 0 && humidity <= 30) {
      list.push({
        id: "sensor-low-humidity",
        title: "Low Humidity",
        message: `Humidity is ${humidity}%. Humidity adjustment may be needed.`,
        level: "warning",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    }

    if (soilTemp >= 32) {
      list.push({
        id: "sensor-high-soil-temp",
        title: "High Soil Temperature",
        message: `Soil temperature is ${soilTemp}°C. Root zone cooling may be required.`,
        level: "warning",
        source: "sensor",
        isRead: false,
        createdAt: latestReading.updatedAt || new Date().toISOString(),
      });
    }
  }

  const highStressDiagnoses = diagnoses.filter((item) => {
    const status = getFinalStatus(item).toLowerCase();
    return status.includes("high") || status.includes("stress");
  });

  const moderateDiagnoses = diagnoses.filter((item) => {
    const status = getFinalStatus(item).toLowerCase();
    return status.includes("moderate");
  });

  if (diagnoses.length === 0) {
    list.push({
      id: "diagnosis-no-records",
      title: "No Diagnosis Records",
      message:
        "No saved diagnoses were found. Run AI diagnosis to generate real plant health history.",
      level: "info",
      source: "diagnosis",
      isRead: false,
      createdAt: new Date().toISOString(),
    });
  }

  if (highStressDiagnoses.length > 0) {
    list.push({
      id: "diagnosis-high-stress",
      title: "High Stress Diagnosis Found",
      message: `${highStressDiagnoses.length} high stress diagnosis result(s) found. Review recommendations and actions.`,
      level: "critical",
      source: "diagnosis",
      isRead: false,
      createdAt:
        getDateValue(highStressDiagnoses[0]) || new Date().toISOString(),
    });
  }

  if (moderateDiagnoses.length > 0) {
    list.push({
      id: "diagnosis-moderate-stress",
      title: "Moderate Stress Detected",
      message: `${moderateDiagnoses.length} moderate stress diagnosis result(s) found. Keep monitoring crop condition.`,
      level: "warning",
      source: "diagnosis",
      isRead: false,
      createdAt: getDateValue(moderateDiagnoses[0]) || new Date().toISOString(),
    });
  }

  if (devices.length === 0) {
    list.push({
      id: "system-no-devices",
      title: "No Devices Registered",
      message:
        "No IoT devices were found for this account. Register hardware devices to complete the system.",
      level: "info",
      source: "system",
      isRead: false,
      createdAt: new Date().toISOString(),
    });
  }

  if (sectors.length === 0) {
    list.push({
      id: "system-no-sectors",
      title: "No Farm Sectors",
      message:
        "No farm sectors were found. Add sectors from web or mobile to organize your farm data.",
      level: "info",
      source: "system",
      isRead: false,
      createdAt: new Date().toISOString(),
    });
  }

  const dashboardAlert =
    dashboard?.alert ||
    dashboard?.latestAlert ||
    dashboard?.criticalAlert ||
    dashboard?.farmAlert;

  if (dashboardAlert) {
    list.push({
      id: "dashboard-alert",
      title: safeText(dashboardAlert?.title) || "Dashboard Alert",
      message:
        safeText(dashboardAlert?.message) ||
        safeText(dashboardAlert) ||
        "Dashboard reported a farm alert.",
      level: normalizeLevel(
        dashboardAlert?.level ||
          dashboardAlert?.severity ||
          dashboardAlert?.type,
      ),
      source: "backend",
      isRead: false,
      createdAt:
        dashboardAlert?.createdAt ||
        dashboardAlert?.updatedAt ||
        new Date().toISOString(),
      raw: dashboardAlert,
    });
  }

  return list.sort((a, b) => {
    const priorityA = getLevelPriority(a.level);
    const priorityB = getLevelPriority(b.level);

    if (priorityA !== priorityB) return priorityB - priorityA;

    const dateA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
    const dateB = b.createdAt ? new Date(b.createdAt).getTime() : 0;

    return dateB - dateA;
  });
}

function getNotificationId(item: any) {
  return safeText(item?._id || item?.id || item?.notificationId);
}

function getDateValue(item: any) {
  return (
    item?.createdAt ||
    item?.updatedAt ||
    item?.date ||
    item?.timestamp ||
    item?.result?.createdAt ||
    null
  );
}

function getFinalStatus(item: any) {
  const result = item?.result || item?.aiResult || item?.analysis || item;

  return (
    safeText(result?.final_status) ||
    safeText(result?.finalStatus) ||
    safeText(result?.status) ||
    safeText(result?.plantStatus) ||
    "Unknown"
  );
}

function normalizeLevel(value: any): "critical" | "warning" | "info" {
  const text = safeText(value).toLowerCase();

  if (
    text.includes("critical") ||
    text.includes("danger") ||
    text.includes("high") ||
    text.includes("urgent") ||
    text.includes("error")
  ) {
    return "critical";
  }

  if (
    text.includes("warning") ||
    text.includes("moderate") ||
    text.includes("medium") ||
    text.includes("alert")
  ) {
    return "warning";
  }

  return "info";
}

function getLevelPriority(level: string) {
  if (level === "critical") return 3;
  if (level === "warning") return 2;
  return 1;
}

function getLevelIcon(level: string) {
  if (level === "critical") return "!";
  if (level === "warning") return "⚠";
  return "i";
}

function getLevelIconStyle(level: string) {
  if (level === "critical") {
    return {
      backgroundColor: "#FEF3F2",
      borderColor: "#FDA29B",
    };
  }

  if (level === "warning") {
    return {
      backgroundColor: "#FFF7E6",
      borderColor: "#F6C56B",
    };
  }

  return {
    backgroundColor: "#E6F7EE",
    borderColor: "#C7EBD8",
  };
}

function getLevelBadgeStyle(level: string) {
  if (level === "critical") {
    return {
      backgroundColor: "#FEF3F2",
      color: "#B42318",
    };
  }

  if (level === "warning") {
    return {
      backgroundColor: "#FFF7E6",
      color: "#B66A00",
    };
  }

  return {
    backgroundColor: "#E6F7EE",
    color: "#118A5B",
  };
}

function formatSource(source: string) {
  if (source === "backend") return "Backend";
  if (source === "sensor") return "Sensors";
  if (source === "diagnosis") return "Diagnosis";
  return "System";
}

function formatDate(value?: string | null) {
  if (!value) return "Now";

  try {
    return new Date(value).toLocaleString();
  } catch {
    return "Now";
  }
}

function safeText(value: any): string {
  if (value === null || value === undefined) return "";

  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "Yes" : "No";

  if (typeof value === "object") {
    return (
      value.name ||
      value.title ||
      value.label ||
      value.message ||
      value.details ||
      value.description ||
      value.status ||
      value.type ||
      value._id ||
      value.id ||
      ""
    );
  }

  return String(value);
}

function safeNumber(value: any) {
  const numberValue = Number(value);
  return Number.isFinite(numberValue) ? numberValue : 0;
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F3F8F1",
  },
  content: {
    padding: 22,
    paddingTop: 50,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#DDE9E2",
  },
  backText: {
    color: "#118A5B",
    fontSize: 14,
    fontWeight: "900",
  },
  refreshButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "#DDE9E2",
  },
  refreshText: {
    color: "#118A5B",
    fontSize: 14,
    fontWeight: "900",
  },
  kicker: {
    color: "#118A5B",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 2,
    marginTop: 26,
  },
  title: {
    color: "#082A1F",
    fontSize: 38,
    fontWeight: "900",
    marginTop: 8,
  },
  subtitle: {
    color: "#65786D",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 18,
  },
  noticeBox: {
    backgroundColor: "#FFF7E6",
    borderColor: "#F6C56B",
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    marginBottom: 16,
  },
  noticeTitle: {
    color: "#B66A00",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 6,
  },
  noticeText: {
    color: "#7A4B00",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  heroCard: {
    backgroundColor: "#0B2A22",
    borderRadius: 30,
    padding: 24,
    marginBottom: 18,
  },
  heroLabel: {
    color: "#8BE0B3",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 1,
  },
  heroNumber: {
    color: "#FFFFFF",
    fontSize: 62,
    fontWeight: "900",
    marginTop: 8,
  },
  heroText: {
    color: "#CFE3D7",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 4,
  },
  heroStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 18,
  },
  miniStat: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  miniValue: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
  },
  dangerText: {
    color: "#FFB4AB",
  },
  warningText: {
    color: "#FFDDA1",
  },
  miniLabel: {
    color: "#CFE3D7",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  filterButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#DDE9E2",
  },
  filterButtonActive: {
    backgroundColor: "#118A5B",
    borderColor: "#118A5B",
  },
  filterText: {
    color: "#65786D",
    fontSize: 13,
    fontWeight: "900",
  },
  filterTextActive: {
    color: "#FFFFFF",
  },
  alertCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: "#DDE9E2",
    marginBottom: 16,
  },
  alertTop: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  levelIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  levelIconText: {
    color: "#0B2A22",
    fontSize: 20,
    fontWeight: "900",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  alertTitle: {
    color: "#0B2A22",
    fontSize: 17,
    fontWeight: "900",
    flex: 1,
  },
  unreadDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#118A5B",
  },
  alertMeta: {
    color: "#7A8B82",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 4,
  },
  levelBadge: {
    overflow: "hidden",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 6,
    fontSize: 10,
    fontWeight: "900",
  },
  alertMessage: {
    color: "#46574D",
    fontSize: 14,
    lineHeight: 22,
    marginTop: 14,
    fontWeight: "700",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  smallButton: {
    flex: 1,
    backgroundColor: "#E6F7EE",
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#C7EBD8",
  },
  smallButtonText: {
    color: "#118A5B",
    fontSize: 13,
    fontWeight: "900",
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#FEF3F2",
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FDA29B",
  },
  deleteButtonText: {
    color: "#B42318",
    fontSize: 13,
    fontWeight: "900",
  },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 26,
    padding: 24,
    borderWidth: 1,
    borderColor: "#DDE9E2",
    alignItems: "center",
    marginBottom: 16,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 24,
    backgroundColor: "#E6F7EE",
    color: "#118A5B",
    textAlign: "center",
    textAlignVertical: "center",
    fontSize: 32,
    fontWeight: "900",
    overflow: "hidden",
    marginBottom: 14,
  },
  emptyTitle: {
    color: "#0B2A22",
    fontSize: 19,
    fontWeight: "900",
  },
  emptyText: {
    color: "#65786D",
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
  },
  quickActions: {
    flexDirection: "row",
    gap: 12,
  },
  actionCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#DDE9E2",
  },
  actionTitle: {
    color: "#0B2A22",
    fontSize: 17,
    fontWeight: "900",
  },
  actionText: {
    color: "#65786D",
    fontSize: 13,
    marginTop: 8,
  },
});
